### ISSUE TITLE
suggestion: composer, phpunit

### ISSUE THREAD

**Issue by pavel-redkin** [stas-bool/test-tasks#1]
Добрый день, Станислав

не рассматривали использовать phpunit для test-case-ов и использовать composer ?
 в phpunit можно использовать вариации assert
также есть поддержка DataProvider - чтоб на нескольких наборах данных протестить код

```
composer.json
/src
/tests
```
разнести код: сам код - в src, тесты - в tests

**Comment by stas-bool** [comment]
Здравствуйте. Изначально так и планировал, но в задачах пример кода был в таком виде. Так и сделал.
